apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-sgx
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 99
  template:
    metadata:
      name: hello-world-sgx
    spec:
      initContainers:
      - name: wait-for-idp
        image: 'registry.redhat.io/rhel9/python-39:latest'
        command:
          - /bin/bash
          - '-c'
          - 'sleep 300'
      containers:
      - name: python
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: LC_ALL
            value: C.utf8
          - name: LANG
            value: C.utf8
        resources:
          requests:
            sgx.intel.com/epc: "1Gi"
          limits:
            sgx.intel.com/epc: "1Gi"
      restartPolicy: OnFailure
